### PR TITLE
Feature/us4-recipe-details

### LINKED ISSUE #206: US4-FE#1 - Add slideshow when clicking recipe's image

### LINKED ISSUE #207: US4-FE#2.1 - Display clicked photo in slideshow

### LINKED ISSUE #208: US4-FE#2.2 - Include additional photos in slideshow

### LINKED ISSUE #209: US4-FE#2.3 - Implement carousel functionality for the slideshow

### LINKED ISSUE #210: US4-FE#3 - Section of similar recipes

### LINKED ISSUE #211: US4-FE#4 - Display 'Related or Similar Recipes' inside the section

### LINKED ISSUE #212: US4-FE#5 - List other recipes by the same user

### LINKED ISSUE #213: US4-FE#6 - Include recipes by users that the current user is following

### LINKED ISSUE #214: US4-FE#7 - Implement new styling for "Reviews" button

### LINKED ISSUE #215: US4-FE#8 - Reformatting of the recipe's author image and username

### PR DESCRIPTION
**Pull request by ivanmansilla**

### CODE REVIEW

**Comment by ivanmansilla** [comment]
Everything that has to do with similar recipes has been implemented once we are inside the detail of a recipe. It is a new section where 6 similar recipes appear, following the same style as the rest of the page and the user feed of how the recipes appear.  If we click on one of them we will be redirected to the recipe in question:
image
image

**Comment by ivanmansilla** [comment]
In agreement with the PO, the design of the similar recipes section has been modified, the title has been enlarged, everything has been put in the same colour... etc.
image

**Review by BlessedLongsword — APPROVED** [review]
I would set the Image component to cover and into a set size for consistency. If an image had a ridiculously big resolution it would break the component. If PO agrees, we can change it. Eithar way, everything seems good

**Comment by ivanmansilla** [comment]
Perfect @BlessedLongsword  I have spoken to the PO and he agrees with what you have said. Here you have the sample that it is already fixed;
image
image

**Pull request merged**
