### PR TITLE
Feature/us8-rate-review-recipes

### LINKED ISSUE #221: US8-FE#1 - Implement red 'Reviews' button on Recipe Details page

### LINKED ISSUE #222: US8-FE#2 - Design Off-Canvas same style

### LINKED ISSUE #223: US8-FE#3 - Display 'Post a Review' Visible for logged-in

### LINKED ISSUE #224: US8-FE#4 - Limit Post Review characters and opinion or review required

### LINKED ISSUE #225: US8-FE#5 - Display Character Count for Review

### LINKED ISSUE #226: US8-FE#6 - Click username of review redirect to UserProfile

### LINKED ISSUE #227: US8-FE#7 - Provide Edit and Delete Options for User's Review

### LINKED ISSUE #229: US8-FE#9 - Owner of recipe -> Disabled Post Review button

### PR DESCRIPTION
**Pull request by ivanmansilla**
In this PR I will upload all the changes and merge the branches that have to do with the rate and review recipes user storie.

### CODE REVIEW

**Comment by ivanmansilla** [comment]
In the reviews of which you are the owner there will now appear two icons, one to edit/modify the review, namely for now the comment and the rating, image below. And the other icon is a bin to delete the recipe. All this has been achieved by creating new components which has taken advantage of one for both and depending on the icon shows a modal or another. 
It is possible that there are still some comments in Spanish, as I will soon change the design and therefore the language and small details.
I attach images:
image
After edit:
image
image
Before delete: 
image

**Comment by ivanmansilla** [comment]
All types of cases have been monitored. If you are the owner of the recipe, the Post review button is disabled, if there are no recipes it shows you that there are no recipes but you can't post reviews as the owner. If there are no recipes and you are not the owner, it tells you that there are no recipes and shows you a new style of offCanvas and offers you to post a review. Finally, I have also modified that the comment does not overlap with the username, and I have changed the design of the Reviews and Post review buttons.
Images:
Button recipeDetail:
image
Buttons and no owner:
image
No owner no recipes:
image
Owner disabled button:
image
Owner no recipes:

**Comment by ivanmansilla** [comment]
If no reviews and is owner the recipe, disabled button: 
image

**Comment by xvxnoah** [comment]
> If no reviews and is owner the recipe, disabled button: 
> 
> image

I would change the text to: "You are the owner of this recipe, so you can't review it!"

**Comment by ivanmansilla** [comment]
Several important changes have been made and several new things have been implemented. The post review, modify review and delete review modes have been redesigned. Also a new review card design has been implemented for reviews without images. In terms of implementation, we have also added a counter that appears below the textarea where in real time it tells you how many characters you have, if you exceed 80, it turns red and you get a message warning you that you have gone too far and disables the post review button or in the case of modify review, the update button. 
I attach images:
New design of Post Review and Modify Review:
image
image
Limit exceeded:
image
image
New style of cards, with image and no image:
image

**Comment by ivanmansilla** [comment]
I have changed the style to match the style of the page.
image
image

**Comment by xvxnoah** [comment]
Good job Ivan!

I will list a couple of changes so that the US aligns with the acceptance criteria we discussed.

1. _Given the user is logged in and on the off-canvas view (and the user is not the owner of the current recipe), then it will be shown a button to post a review. The button will be red with a white text "Post a review"._

As of now, the text says "Post review" which I think can be confusing:
Screenshot 2023-12-13 at 20 10 00

2. _Given the user is writing a review, then a backwards character counter should be visible, limiting the review to a specific number of characters (i.e., 120)_.

Now the counter sums up the current count of characters, but I believe a backwards counter (characters remaining), would be more visual.
Screenshot 2023-12-13 at 20 10 21

3. _Given a user submits a review and clicks the "Reviews" button, then the review should appear in a list format showing the username (clickable, redirecting to the user's profile), the rating given (in start format, the stars being red, and the icon being a red checkmark), the review text (if provided), the image (if provided), and the number of likes the review has received (with an icon of a red heart)_.

Regarding this acceptance criteria we lack the ability to press on the username and be redirected to the user profile.
Screenshot 2023-12-13 at 20 10 43

4. _Given a user views a review, when they find it helpful, then they should have the option to click a "like" button (icon of a red heart) associated with the review_.

Here the colour of the heart should be red, as mentioned in the acceptance criteria.
Screenshot 2023-12-13 at 20 10 52

5. _Given a user attempts to rate or review a recipe they've already rated or reviewed, when they do not choose the edit option, then the platform should display a notification pop up reminding them of their previous action (i.e., saying "You have already reviewed this recipe!")_.

As of now the error is not represented as the acceptance criteria asks: "You have already reviewed this recipe!", and the modal of the error (or the pop up) should be in the same colour style.
Screenshot 2023-12-13 at 20 06 28

**Comment by xvxnoah** [comment]
> Good job Ivan!
> 
> I will list a couple of changes so that the US aligns with the acceptance criteria we discussed.
> 
> 1. _Given the user is logged in and on the off-canvas view (and the user is not the owner of the current recipe), then it will be shown a button to post a review. The button will be red with a white text "Post a review"._
> 
> As of now, the text says "Post review" which I think can be confusing: Screenshot 2023-12-13 at 20 10 00
> 
> 2. _Given the user is writing a review, then a backwards character counter should be visible, limiting the review to a specific number of characters (i.e., 120)_.
> 
> Now the counter sums up the current count of characters, but I believe a backwards counter (characters remaining), would be more visual. Screenshot 2023-12-13 at 20 10 21
> 
> 3. _Given a user submits a review and clicks the "Reviews" button, then the review should appear in a list format showing the username (clickable, redirecting to the user's profile), the rating given (in start format, the stars being red, and the icon being a red checkmark), the review text (if provided), the image (if provided), and the number of likes the review has received (with an icon of a red heart)_.
> 
> Regarding this acceptance criteria we lack the ability to press on the username and be redirected to the user profile. Screenshot 2023-12-13 at 20 10 43
> 
> 4. _Given a user views a review, when they find it helpful, then they should have the option to click a "like" button (icon of a red heart) associated with the review_.
> 
> Here the colour of the heart should be red, as mentioned in the acceptance criteria. Screenshot 2023-12-13 at 20 10 52
> 
> 5. _Given a user attempts to rate or review a recipe they've already rated or reviewed, when they do not choose the edit option, then the platform should display a notification pop up reminding them of their previous action (i.e., saying "You have already reviewed this recipe!")_.
> 
> As of now the error is not represented as the acceptance criteria asks: "You have already reviewed this recipe!", and the modal of the error (or the pop up) should be in the same colour style. Screenshot 2023-12-13 at 20 06 28

For the last one I mentioned, I think it would be nicer to have a pop up.

**Comment by ivanmansilla** [comment]
WIP: 
Currently it is already ready in the feature/changes-demo branch, the counter from 120 to 0 that you told me @xvxnoah , also that Post a review appears. Here is a sample, as soon as I can I will finish the other points, thanks!
image
image
image

**Review by BlessedLongsword — DISMISSED** [review]

**Comment by ivanmansilla** [comment]
I have finally finished all the acceptances criteria and fixed the things the PO told me. Right now apart from the previous comment, the likes have a different design, if you don't have the like on it is just the heart in the outline, and if we give you like it is a full heart. Also the pop up that appears when we try to review a recipe that we have already reviewed before has been redesigned:
image
image

**Review by xvxnoah — DISMISSED** [review]
Good job Ivan!

**Review by xvxnoah — APPROVED** [review]

**Pull request merged**
